application: rastercrafter
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /([^/]*\.(.*))
  static_files: static/\2/\1
  upload: static/(.*?)/(.*)

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
